### ISSUE TITLE
References: object vs array?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csl-next#47]
Just occurred to me, so noting ...

A citekey is a unique identifier for a reference. In the current model, `ID` is a required property on `Reference`, which is collected in `Bibliography` under `references`, which is an array.

But an object or dictionary better matches the actual data:

```yaml
references:
  doe1:
    title: Some Title
```

It's also more performant for lookup; [this article](https://javascript.plainenglish.io/performance-of-arrays-and-objects-in-javascript-through-the-lens-of-big-o-5a7c5891a43f), for example, concludes:

> ... working objects is comparatively much faster than the arrays when we don’t need orders.

Perhaps the input model should be the former, and a processor should simply transform it to a list for intermediate processing?

Aside: my initial implementation of what became CSL was XSLT 1.0, which is a purely functional language. So the processing there was all about transforming lists into other lists.

**Comment by denismaier** [comment]
> Perhaps the input model should be the former, and a processor should simply transform it to a list for intermediate processing?

Yes, this make sense. Maybe there are some drawbacks I'm not aware of, but I'd say this makes it easier (and faster) to work with the data overall.

**Comment by bdarcus** [comment]
It occurred to me it's an array now because it was designed around Zotero, where they know the size of the array they're feeding the processor, and it's unlikely to be huge.

In a batch context like pandoc etc, where users may be using such a file as their database, that's not the case.

But I think a hybrid approach can work.

--------------------

May as well experiment with it :-)

```js
const object1 = {
  a: {'id': 'a', 'title': "A Title"},
  b: {'id': 'b', 'title': "Another Title"}
};

const array1 = Object.values(object1)

console.log(array1);
```

Or maybe the array would just contain the intermediate processing data (disambiguation data, etc.), and a pointer back to the object? So pull only the keys from the object that are cited, and then process them into an array a more minimal array?

I guess in the end the answer is more  a performance question than anything.
